const bookList = [
  { id: 1, title: 'A Short History of Nearly Everything', author: 'Bill Bryson', genres: ['Popular Science', 'Non-fiction', 'History'] },
  { id: 2, title: 'A Tree Grows in Brooklyn', author: 'Betty Smith', genres: ['Fiction', 'Historical Fiction', 'Coming Of Age'] },
  { id: 3, title: 'Algorithm Design', author: 'Jon Kleinberg & Éva Tardos', genres: ['Computer Science', 'Algorithms', 'Nonfiction'] },
  { id: 4, title: 'Algorithms', author: 'Robert Sedgewick & Kevin Wayne', genres: ['Computer Science', 'Algorithms', 'Nonfiction'] },
  { id: 5, title: 'American Psycho', author: 'Bret Easton Ellis', genres: ['Fiction', 'Satire', 'Horror'] },
  { id: 6, title: 'Blink', author: 'Malcolm Gladwell', genres: ['Non-fiction', 'Psychology', 'Social Science'] },
  { id: 7, title: 'Brave New World', author: 'Aldous Huxley', genres: ['Science Fiction', 'Dystopian Fiction', 'Novel'] },
  { id: 8, title: 'Calculus Made Easy', author: 'Silvanus P. Thompson', genres: ['Mathematics', 'Calculus', 'Education'] },
  { id: 9, title: 'Call Us What We Carry', author: 'Amanda Gorman', genres: ['Poetry'] },
  { id: 10, title: 'Catch-22', author: 'Joseph Heller', genres: ['Dark Comedy', 'Satire', 'War Fiction'] },
  { id: 11, title: 'Clean Architecture', author: 'Robert C. Martin', genres: ['Programming', 'Software Development', 'Computer Science'] },
  { id: 12, title: 'Clean Code', author: 'Robert C. Martin', genres: ['Programming', 'Computer Science', 'Software Development'] },
  { id: 13, title: 'Code Complete 2', author: 'Steve McConnell', genres: ['Programming', 'Computer Science', 'Nonfiction'] },
  { id: 14, title: 'Desert Solitaire', author: 'Edward Abbey', genres: ['Memoir', 'Nature Writing', 'Environmentalism'] },
  { id: 15, title: 'Drive', author: 'Daniel H. Pink', genres: ['Non-fiction', 'Business', 'Psychology'] },
  { id: 16, title: 'Effective Java', author: 'Joshua Bloch', genres: ['Programming', 'Computer Science', 'Nonfiction'] },
  { id: 17, title: 'Elements of Programming Interviews in Java', author: 'Adnan Aziz, Tsung-Hsien Lee, Amit Prakash', genres: ['Programming', 'Algorithms', 'Technical Interview Preparation'] },
  { id: 18, title: 'Five Tuesdays in Winter', author: 'Lily King', genres: ['Short Fiction', 'Literary Fiction', 'Contemporary'] },
  { id: 19, title: 'Freakonomics', author: 'Steven D. Levitt & Stephen J. Dubner', genres: ['Non-fiction', 'Economics', 'Social Science'] },
  { id: 20, title: 'Fundamentals of Software Architecture', author: 'Mark Richards & Neal Ford', genres: ['Computer Science', 'Systems Architecture', 'Software Development'] },
  { id: 21, title: 'Gödel, Escher, Bach', author: 'Douglas R. Hofstadter', genres: ['Nonfiction', 'Philosophy', 'Computer Science'] },
  { id: 22, title: 'Hackers & Painters', author: 'Paul Graham', genres: ['Non-Fiction', 'Technology', 'Computer Science'] },
  { id: 23, title: 'Head First Design Patterns', author: 'Eric Freeman, Elisabeth Robson', genres: ['Programming', 'Computer Science', 'Non-fiction'] },
  { id: 24, title: 'Head First Java', author: 'Kathy Sierra & Bert Bates', genres: ['Programming', 'Computer Science', 'Nonfiction'] },
  { id: 25, title: 'Head First Object-Oriented Analysis & Design', author: 'Brett D. McLaughlin, Gary Pollice, David West', genres: ['Computer Science', 'Programming', 'Software Development'] },
  { id: 26, title: 'Hillbilly Elegy', author: 'J.D. Vance', genres: ['Memoir', 'Non-fiction'] },
  { id: 27, title: 'Home Body', author: 'Rupi Kaur', genres: ['Poetry'] },
  { id: 28, title: 'House of God', author: 'Samuel Shem', genres: ['Fiction', 'Medical Fiction', 'Satire'] },
  { id: 29, title: 'House of Leaves', author: 'Mark Z. Danielewski', genres: ['Horror', 'Metafiction', 'Postmodern Literature'] },
  { id: 30, title: 'How I Built This', author: 'Guy Raz', genres: ['Business', 'Entrepreneurship', 'Non-fiction'] },
  { id: 31, title: 'How to Be Interesting', author: 'Jessica Hagy', genres: ['Non-fiction', 'Self-Help', 'Humor'] },
  { id: 32, title: 'How to Stay Alive in the Woods', author: 'Bradford Angier', genres: ['Non-fiction', 'Outdoor Skills', 'Survival'] },
  { id: 33, title: 'How to Win Friends & Influence People', author: 'Dale Carnegie', genres: ['Self-help', 'Business', 'Personal Development'] },
  { id: 34, title: 'HTML and CSS: Design and Build Websites', author: 'Jon Duckett', genres: ['Programming', 'Nonfiction', 'Web Design'] },
  { id: 35, title: 'Introductory Graph Theory', author: 'Gary Chartrand', genres: ['Mathematics', 'Computer Science', 'Nonfiction'] },
  { id: 36, title: 'It', author: 'Stephen King', genres: ['Horror', 'Fiction', 'Thriller'] },
  { id: 37, title: 'Java Puzzlers', author: 'Joshua Bloch & Neal Gafter', genres: ['Programming', 'Computer Science', 'Technology'] },
  { id: 38, title: 'JavaScript and JQuery', author: 'Jon Duckett', genres: ['Programming', 'Technology', 'Web Development'] },
  { id: 39, title: 'Learn to Produce Videos with FFmpeg', author: 'Jan Ozer', genres: ['Computers', 'Video & Animation', 'Technology'] },
  { id: 40, title: 'Make Your Bed', author: 'William H. McRaven', genres: ['Self-help', 'Personal Growth', 'Motivational'] },
  { id: 41, title: 'Maybe You Should Talk to Someone', author: 'Lori Gottlieb', genres: ['Memoir', 'Non-fiction', 'Psychology'] },
  { id: 42, title: 'Missoula', author: 'Jon Krakauer', genres: ['Non-fiction', 'True Crime'] },
  { id: 43, title: 'Neuromancer', author: 'William Gibson', genres: ['Science Fiction', 'Cyberpunk', 'Novel'] },
  { id: 44, title: 'Never Eat Alone', author: 'Keith Ferrazzi', genres: ['Business', 'Nonfiction', 'Self-Help'] },
  { id: 45, title: 'Object-Oriented Design Heuristics', author: 'Arthur J. Riel', genres: ['Computer Science', 'Programming', 'Software Development'] },
  { id: 46, title: 'On Intelligence', author: 'Jeff Hawkins', genres: ['Psychology', 'Nonfiction', 'Neuroscience'] },
  { id: 47, title: 'One-Star Romance', author: 'Laura Hankin', genres: ['Fiction', 'Romance', 'Contemporary'] },
  { id: 48, title: 'Play Winning Chess', author: 'Yasser Seirawan', genres: ['Games', 'Chess'] },
  { id: 49, title: 'Programming Pearls', author: 'Jon Bentley', genres: ['Programming', 'Computer Science', 'Nonfiction'] },
  { id: 50, title: 'Psycho-Cybernetics', author: 'Maxwell Maltz', genres: ['Self-help', 'Psychology', 'Personal Development'] },
  { id: 51, title: 'Q84', author: 'Haruki Murakami', genres: ['Fiction', 'Alternate History', 'Magical Realism'] },
  { id: 52, title: 'Surely You\'re Joking, Mr. Feynman!', author: 'Richard P. Feynman', genres: ['Biography', 'Memoir', 'Science'] },
  { id: 53, title: 'Slade House', author: 'David Mitchell', genres: ['Horror', 'Drama', 'Mystery'] },
  { id: 54, title: 'Spark', author: 'John J. Ratey', genres: ['Non-fiction', 'Health & Fitness', 'Neuroscience'] },
  { id: 55, title: 'Start with Why', author: 'Simon Sinek', genres: ['Business', 'Leadership', 'Self-Help'] },
  { id: 56, title: 'The Shining', author: 'Stephen King', genres: ['Horror', 'Fiction', 'Psychological Thriller'] },
  { id: 57, title: 'The 4-Hour Workweek', author: 'Timothy Ferriss', genres: ['Self-help', 'Business', 'Non-fiction'] },
  { id: 58, title: 'The 7 Habits of Highly Effective People', author: 'Stephen R. Covey', genres: ['Self-help', 'Business', 'Personal Development'] },
  { id: 59, title: 'The Algorithm Design Manual', author: 'Steven S. Skiena', genres: ['Computer Science', 'Algorithms', 'Nonfiction'] },
  { id: 60, title: 'The Body', author: 'Bill Bryson', genres: ['Non-fiction', 'Science', 'Health'] },
  { id: 61, title: 'The Cyclist\'s Training Bible', author: 'Joe Friel', genres: ['Sports', 'Non-fiction', 'Health & Fitness'] },
  { id: 62, title: 'The Design of Everyday Things', author: 'Don Norman', genres: ['Design', 'Psychology', 'Non-fiction'] },
  { id: 63, title: 'The Elements of Computing Systems', author: 'Noam Nisan and Shimon Schocken', genres: ['Technology', 'Computer Science', 'Programming'] },
  { id: 64, title: 'The First Man', author: 'Albert Camus', genres: ['Fiction', 'Coming-of-Age', 'Philosophical Fiction'] },
  { id: 65, title: 'The Giving Tree', author: 'Shel Silverstein', genres: ['Children\'s Literature', 'Fiction'] },
  { id: 66, title: 'The Headspace Guide to Meditation & Mindfulness', author: 'Andy Puddicombe', genres: ['Nonfiction', 'Self-Help', 'Psychology'] },
  { id: 67, title: 'The Institute', author: 'Stephen King', genres: ['Horror', 'Thriller', 'Science Fiction'] },
  { id: 68, title: 'The Jungle', author: 'Upton Sinclair', genres: ['Fiction', 'Historical Fiction', 'Social Commentary'] },
  { id: 69, title: 'The Knowledge Gap', author: 'Natalie Wexler', genres: ['Education', 'Non-fiction', 'Educational Policy'] },
  { id: 70, title: 'The Lean Startup', author: 'Eric Ries', genres: ['Business', 'Non-fiction', 'Entrepreneurship'] },
  { id: 71, title: 'The Little Prince', author: 'Antoine de Saint-Exupéry', genres: ['Novella', 'Children\'s Literature', 'Philosophical Fiction'] },
  { id: 72, title: 'The Moment of Lift', author: 'Melinda Gates', genres: ['Social Science', 'Non-fiction', 'Women\'s Studies'] },
  { id: 73, title: 'The Motivation Hacker', author: 'Nick Winter', genres: ['Self-Help', 'Psychology', 'Productivity'] },
  { id: 74, title: 'The Old Man and the Sea', author: 'Ernest Hemingway', genres: ['Novel', 'Nautical Fiction', 'Literary Fiction'] },
  { id: 75, title: 'The Personal MBA', author: 'Josh Kaufman', genres: ['Business', 'Self-Help', 'Non-fiction'] },
  { id: 76, title: 'The Pragmatic Programmer', author: 'Andrew Hunt and David Thomas', genres: ['Programming', 'Technology', 'Software Development'] },
  { id: 77, title: 'The Productivity Project', author: 'Chris Bailey', genres: ['Self-Help', 'Nonfiction', 'Business'] },
  { id: 78, title: 'The Rosie Effect', author: 'Graeme Simsion', genres: ['Romance', 'Fiction', 'Contemporary'] },
  { id: 79, title: 'The Speed of Trust', author: 'Stephen M. R. Covey', genres: ['Business', 'Self-Help', 'Leadership'] },
  { id: 80, title: 'The Subtle Art of Not Giving a F*ck', author: 'Mark Manson', genres: ['Nonfiction', 'Self-help', 'Psychology'] },
  { id: 81, title: 'The Sun and Her Flowers', author: 'Rupi Kaur', genres: ['Poetry'] },
  { id: 82, title: 'The Things They Carried', author: 'Tim O\'Brien', genres: ['Fiction', 'War Story', 'Short Stories'] },
  { id: 83, title: 'Thing Explainer', author: 'Randall Munroe', genres: ['Non-fiction', 'Science', 'Humor'] },
  { id: 84, title: 'Thinking, Fast and Slow', author: 'Daniel Kahneman', genres: ['Non-fiction', 'Psychology', 'Economics'] },
  { id: 85, title: 'Tom Lake', author: 'Ann Patchett', genres: ['Fiction', 'Contemporary', 'Literary Fiction'] },
  { id: 86, title: 'Trust', author: 'Hernan Diaz', genres: ['Historical Fiction', 'Literary Fiction'] },
  { id: 87, title: 'UNIX: A History and a Memoir', author: 'Brian Kernighan', genres: ['Technology', 'Computer Science', 'History'] },
  { id: 88, title: 'Walden', author: 'Henry David Thoreau', genres: ['Autobiography', 'Memoir', 'Philosophy'] },
  { id: 89, title: 'What I Talk About When I Talk About Running', author: 'Haruki Murakami', genres: ['Memoir', 'Non-fiction', 'Running'] },
  { id: 90, title: 'What to Say When You Talk to Your Self', author: 'Shad Helmstetter', genres: ['Self-help', 'Psychology', 'Nonfiction'] },
  { id: 91, title: 'Why We Sleep', author: 'Matthew Walker', genres: ['Science', 'Non-fiction', 'Health'] },
  { id: 92, title: 'Writing Compilers and Interpreters', author: 'Ronald Mak', genres: ['Programming', 'Software Development', 'Computer Science'] },
  { id: 93, title: 'Zero to One', author: 'Peter Thiel with Blake Masters', genres: ['Business', 'Entrepreneurship', 'Non-fiction'] }
];

exports.default = bookList;
